#!/bin/sh

if ! [ -f $6 ]
then
  cat $5 > $6
fi

s=`grep -c "$2     --- $3" $6`

if [ $s = "0" ]
then
  if [ "$BASH_VERSION" ]; then
    echo -e "        $1   $2     --- $3 $4" >> $6
# on some systems use echo without '-e'
# uncomment the next line
  else
    echo "        $1   $2     --- $3 $4" >> $6
  fi
fi
